<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing products
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Product::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $products = [
            [
                'name' => 'Honda Beat FI 2022',
                'brand' => 'Honda',
                'type' => 'Matic',
                'cc' => 110,
                'price' => 14500000,
                'year_manufacture' => 2022,
                'year_assembly' => 2022,
                'color' => 'Hitam Glossy',
                'odometer' => 5400,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                
                // Condition (Grade A target)
                'engine_sound' => 'Normal',
                'oil_leak' => 'Kering',
                'exhaust_smoke' => 'Normal',
                'engine_pull' => 'Responsif',
                'body_condition' => 'Mulus',
                'frame_condition' => 'Normal',
                'legs_condition' => 'Stabil',
                'electrical_condition' => 'Normal',
                
                // Docs
                'stnk_status' => 'Ada',
                'bpkb_status' => 'Ada',
                'tax_status' => 'Hidup',
                'tax_expiry' => '2025-08-20',
                'plate_number_status' => 'Asli',
                
                // History
                'routine_service' => true,
                'service_book' => true,
                'accident_history' => false,
                'flood_history' => false,
                'engine_overhaul' => false,
                
                // Extras
                'spare_key' => true,
                'toolkit' => true,
                'manual_book' => true,
                'bonus_helmet' => true,
                
                'short_description' => 'Motor matic sejuta umat, kondisi istimewa seperti baru. KM rendah.',
                'description' => "Honda Beat FI 2022 tipe CBS-ISS.\nKondisi sangat terawat, pemakaian pribadi wanita.\nServis rutin di bengkel resmi Honda (AHASS).\nBan depan belakang masih tebal.\nTidak ada PR, siap pakai gaspol.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Yamaha NMAX 155 ABS 2020',
                'brand' => 'Yamaha',
                'type' => 'Matic',
                'cc' => 155,
                'price' => 28500000,
                'year_manufacture' => 2020,
                'year_assembly' => 2020,
                'color' => 'Matte Black',
                'odometer' => 22000,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                
                // Condition (Grade B target - minor issues)
                'engine_sound' => 'Normal',
                'oil_leak' => 'Kering',
                'exhaust_smoke' => 'Normal',
                'engine_pull' => 'Responsif',
                'body_condition' => 'Lecet Pemakaian',
                'frame_condition' => 'Normal',
                'legs_condition' => 'Stabil',
                'electrical_condition' => 'Normal',
                
                'stnk_status' => 'Ada',
                'bpkb_status' => 'Ada',
                'tax_status' => 'Hidup',
                'tax_expiry' => '2024-12-15',
                'plate_number_status' => 'Asli',
                
                'routine_service' => true,
                'service_book' => true,
                'accident_history' => false,
                'flood_history' => false,
                
                'spare_key' => true,
                'toolkit' => true,
                'manual_book' => false,
                'bonus_helmet' => false,
                
                'short_description' => 'NMAX ABS nyaman untuk touring atau harian. Body mulus 90%.',
                'description' => "Yamaha NMAX 155 ABS Connected.\nFitur lengkap: Keyless, Traction Control, ABS Dual Channel.\nBody ada lecet halus pemakaian wajar di bagian samping.\nMesin halus, CVT aman tidak gredek.\nBaru ganti v-belt dan roller.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Kawasaki KLX 150 BF 2019',
                'brand' => 'Kawasaki',
                'type' => 'Trail',
                'cc' => 150,
                'price' => 24000000,
                'year_manufacture' => 2019,
                'year_assembly' => 2019,
                'color' => 'Hijau',
                'odometer' => 15000,
                'usage_type' => 'Touring',
                'usage_location' => 'Luar Kota',
                
                // Condition (Grade B - Modified)
                'engine_sound' => 'Normal',
                'oil_leak' => 'Kering',
                'exhaust_smoke' => 'Normal',
                'engine_pull' => 'Responsif',
                'body_condition' => 'Lecet Pemakaian',
                'frame_condition' => 'Normal',
                'legs_condition' => 'Stabil',
                'electrical_condition' => 'Normal',
                
                'stnk_status' => 'Ada',
                'bpkb_status' => 'Ada',
                'tax_status' => 'Hidup',
                'tax_expiry' => '2025-02-10',
                'plate_number_status' => 'Asli',
                
                'exhaust_type' => 'Racing',
                'modifications' => 'Knalpot Norifumi, Stang Protaper, Velg 18-21',
                'modifications_legal' => true,
                
                'routine_service' => false,
                'service_book' => false,
                'accident_history' => false,
                'flood_history' => false,
                
                'spare_key' => false,
                'toolkit' => true,
                
                'short_description' => 'Motor trail siap trabas. Full modif branded.',
                'description' => "Kawasaki KLX 150 BF Extreme.\nSudah modifikasi proper untuk trabas ringan.\nMesin standar ting-ting, belum pernah boreup.\nKnalpot ori masih ada tersimpan rapi.\nSurat-surat lengkap akur.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Honda Vario 125 Old 2014',
                'brand' => 'Honda',
                'type' => 'Matic',
                'cc' => 125,
                'price' => 9500000,
                'year_manufacture' => 2014,
                'year_assembly' => 2014,
                'color' => 'Putih',
                'odometer' => 68000,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                
                // Condition (Grade C - Old, Tax Dead)
                'engine_sound' => 'Normal',
                'oil_leak' => 'Rembes',
                'exhaust_smoke' => 'Normal',
                'engine_pull' => 'Berat',
                'body_condition' => 'Lecet Pemakaian',
                'frame_condition' => 'Normal',
                'legs_condition' => 'Oblak',
                'electrical_condition' => 'Normal',
                
                'stnk_status' => 'Ada',
                'bpkb_status' => 'Ada',
                'tax_status' => 'Mati',
                'tax_expiry' => '2023-05-20',
                'plate_number_status' => 'Asli',
                
                'routine_service' => false,
                'service_book' => false,
                
                'short_description' => 'Vario 125 bohlam, mesin bandel. Pajak off 1 tahun.',
                'description' => "Honda Vario 125 Techno (Vario Bohlam).\nMesin masih enak dipakai harian.\nMinus: Pajak mati 1x, shockbreaker belakang agak keras, ada rembes oli sedikit di cvt.\nCocok untuk bahan restorasi atau motor tempur harian.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Yamaha Mio Sporty 2010',
                'brand' => 'Yamaha',
                'type' => 'Matic',
                'cc' => 115,
                'price' => 4500000,
                'year_manufacture' => 2010,
                'year_assembly' => 2010,
                'color' => 'Merah',
                'odometer' => 85000,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                
                // Condition (Grade D - Poor condition)
                'engine_sound' => 'Menggelitik',
                'oil_leak' => 'Bocor',
                'exhaust_smoke' => 'Putih',
                'engine_pull' => 'Berat',
                'body_condition' => 'Lecet Parah',
                'frame_condition' => 'Karat',
                'legs_condition' => 'Oblak',
                'electrical_condition' => 'Perlu Perbaikan',
                
                'stnk_status' => 'Ada',
                'bpkb_status' => 'Ada',
                'tax_status' => 'Mati',
                'tax_expiry' => '2020-01-01',
                'plate_number_status' => 'Asli',
                
                'routine_service' => false,
                'service_book' => false,
                'accident_history' => false,
                
                'short_description' => 'Mio Smile bahan. Mesin perlu perbaikan. Surat lengkap.',
                'description' => "Jual apa adanya Yamaha Mio Sporty (Mio Smile).\nMesin ngebul asap putih, perlu servis besar/overhaul.\nBody banyak lecet dan ada pecah dikit.\nPajak mati lama.\nHanya untuk yang mengerti barang atau mau bangun ulang.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Vespa Sprint S 150 2023',
                'brand' => 'Vespa',
                'type' => 'Matic',
                'cc' => 150,
                'price' => 55000000,
                'year_manufacture' => 2023,
                'year_assembly' => 2023,
                'color' => 'Grey',
                'odometer' => 1200,
                'usage_type' => 'Jarang Pakai',
                'usage_location' => 'Dalam Kota',
                
                // Condition (Grade A - Perfect)
                'engine_sound' => 'Normal',
                'oil_leak' => 'Kering',
                'exhaust_smoke' => 'Normal',
                'engine_pull' => 'Responsif',
                'body_condition' => 'Mulus',
                'frame_condition' => 'Normal',
                'legs_condition' => 'Stabil',
                'electrical_condition' => 'Normal',
                
                'stnk_status' => 'Ada',
                'bpkb_status' => 'Ada',
                'tax_status' => 'Hidup',
                'tax_expiry' => '2024-11-11',
                'plate_number_status' => 'Asli',
                
                'routine_service' => true,
                'service_book' => true,
                
                'spare_key' => true,
                'toolkit' => true,
                'manual_book' => true,
                'bonus_helmet' => true,
                
                'short_description' => 'Vespa Sprint S Like New! KM 1000 perak. Masih bau dealer.',
                'description' => "Vespa Sprint S 150 i-get ABS.\nKondisi 99% seperti baru keluar dari dealer.\nJarang dipakai, cuma dipanasin aja.\nFull original, tidak ada modif aneh-aneh.\nKunci coklat & biru lengkap.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Honda CBR 250RR 2018',
                'brand' => 'Honda',
                'type' => 'Sport',
                'cc' => 250,
                'price' => 42000000,
                'year_manufacture' => 2018,
                'year_assembly' => 2018,
                'color' => 'Matte Gunpowder Black',
                'odometer' => 28000,
                'usage_type' => 'Touring',
                'usage_location' => 'Luar Kota',
                
                // Condition (Grade B)
                'engine_sound' => 'Normal',
                'oil_leak' => 'Kering',
                'exhaust_smoke' => 'Normal',
                'engine_pull' => 'Responsif',
                'body_condition' => 'Lecet Pemakaian',
                'frame_condition' => 'Normal',
                'legs_condition' => 'Stabil',
                'electrical_condition' => 'Normal',
                
                'stnk_status' => 'Ada',
                'bpkb_status' => 'Ada',
                'tax_status' => 'Hidup',
                'tax_expiry' => '2025-06-30',
                'plate_number_status' => 'Asli',
                
                'exhaust_type' => 'Racing',
                'modifications' => 'Knalpot R9, Frame Slider, Single Seat',
                
                'short_description' => 'CBR 250RR tampan berani. Total control. Siap sunmori.',
                'description' => "Honda CBR 250RR 2 Cylinder.\nPerforma mesin sangat sehat, selalu pakai Pertamax Turbo.\nSudah ada beberapa part modifikasi (part ori ada).\nBody mulus, ada baret halus di fairing bawah wajar pemakaian.\nBan Battlax masih tebal.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Suzuki Satria F150 2015',
                'brand' => 'Suzuki',
                'type' => 'Bebek',
                'cc' => 150,
                'price' => 11000000,
                'year_manufacture' => 2015,
                'year_assembly' => 2015,
                'color' => 'Hitam Merah',
                'odometer' => 45000,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                
                // Condition (Grade C)
                'engine_sound' => 'Menggelitik',
                'oil_leak' => 'Kering',
                'exhaust_smoke' => 'Normal',
                'engine_pull' => 'Responsif',
                'body_condition' => 'Repaint',
                'frame_condition' => 'Normal',
                'legs_condition' => 'Stabil',
                'electrical_condition' => 'Normal',
                
                'stnk_status' => 'Ada',
                'bpkb_status' => 'Ada',
                'tax_status' => 'Hidup',
                'tax_expiry' => '2025-03-15',
                'plate_number_status' => 'Asli',
                
                'modifications' => 'Velg Repaint, Underbone',
                'routine_service' => false,
                'service_book' => false,
                'accident_history' => false,
                'flood_history' => false,
                'engine_overhaul' => false,
                'spare_key' => false,
                'toolkit' => true,
                'manual_book' => false,
                'bonus_helmet' => false,
                
                'short_description' => 'Satria Fu Karbu terakhir. Tenaga joss.',
                'description' => "Suzuki Satria F150 Facelift.\nMesin standar, suara agak kasar dikit di head (ciri khas satria).\nBody sudah repaint rapi.\nSurat-surat lengkap pajak hidup panjang.\nKelistrikan normal starter tokcer.",
                'image' => 'products/beat_2022.jpg'
            ],
            // === MOCIL & MATIC ===
            [
                'name' => 'Honda Monkey 125 2021',
                'brand' => 'Honda',
                'type' => 'Sport',
                'cc' => 125,
                'price' => 75000000,
                'year_manufacture' => 2021,
                'year_assembly' => 2021,
                'color' => 'Banana Yellow',
                'odometer' => 800,
                'usage_type' => 'Jarang Pakai',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Mulus', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-06-01', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => true,
                'short_description' => 'Mocil hobi kolektor item. Kondisi perfect.',
                'description' => "Honda Monkey 125 CBU.\nMotor simpanan, jarang keluar garasi.\nFull original paint, no lecet.\nCocok untuk investasi atau pajangan ruang tamu.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Kawasaki KSR 110 Pro 2014',
                'brand' => 'Kawasaki',
                'type' => 'Sport',
                'cc' => 110,
                'price' => 18500000,
                'year_manufacture' => 2014,
                'year_assembly' => 2014,
                'color' => 'Hijau',
                'odometer' => 12000,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Rembes', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Lecet Pemakaian', 'frame_condition' => 'Normal', 'legs_condition' => 'Oblak', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Mati', 'tax_expiry' => '2023-04-10', 'plate_number_status' => 'Asli',
                'routine_service' => false, 'service_book' => false, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => false, 'toolkit' => true, 'manual_book' => false, 'bonus_helmet' => false,
                'short_description' => 'Minimoto asik buat harian. Pajak off.',
                'description' => "Kawasaki KSR 110 Pro (Kopling Manual).\nMesin enak, tarikan responsif.\nMinus: Seal shock depan rembes, pajak mati 2 tahun.\nBan masih tebal, siap pakai sunmori tipis-tipis.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Yamaha Fazzio Neo 2022',
                'brand' => 'Yamaha',
                'type' => 'Matic',
                'cc' => 125,
                'price' => 19500000,
                'year_manufacture' => 2022,
                'year_assembly' => 2022,
                'color' => 'Cyan',
                'odometer' => 6500,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Mulus', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-08-17', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => true,
                'short_description' => 'Matic hybrid kekinian. Irit dan stylish.',
                'description' => "Yamaha Fazzio Neo Hybrid Connected.\nWarna favorit Cyan.\nKondisi body 98% mulus, baret halus di spion aja.\nServis rutin Yamaha, garansi mesin masih berlaku.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Honda Genio 2019',
                'brand' => 'Honda',
                'type' => 'Matic',
                'cc' => 110,
                'price' => 13500000,
                'year_manufacture' => 2019,
                'year_assembly' => 2019,
                'color' => 'Hitam Merah',
                'odometer' => 18000,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Lecet Pemakaian', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-01-20', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => false, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => false, 'toolkit' => true, 'manual_book' => false, 'bonus_helmet' => false,
                'short_description' => 'Matic compact irit bensin. Rangka eSAF aman.',
                'description' => "Honda Genio CBS.\nBody ada lecet pemakaian wajar parkiran.\nRangka sudah dicek di AHASS aman tidak karat/keropos (ada buktinya).\nMesin halus, siap pakai kerja.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Yamaha XMAX 250 2018',
                'brand' => 'Yamaha',
                'type' => 'Matic',
                'cc' => 250,
                'price' => 48000000,
                'year_manufacture' => 2018,
                'year_assembly' => 2018,
                'color' => 'Bronze',
                'odometer' => 35000,
                'usage_type' => 'Touring',
                'usage_location' => 'Luar Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Lecet Pemakaian', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-07-10', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => false,
                'short_description' => 'Matic bongsor nyaman touring. Ready gas.',
                'description' => "Yamaha XMAX 250.\nMesin standar ting-ting, belum pernah oprek.\nKampas rem baru ganti depan belakang.\nBan Pirelli Diablo Scooter masih tebal.\nLecet pemakaian di body samping.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Honda Forza 250 2021',
                'brand' => 'Honda',
                'type' => 'Matic',
                'cc' => 250,
                'price' => 72000000,
                'year_manufacture' => 2021,
                'year_assembly' => 2021,
                'color' => 'Silver Metallic',
                'odometer' => 9000,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Mulus', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-09-05', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => true,
                'short_description' => 'Matic premium CBU Thailand. Mewah dan langka.',
                'description' => "Honda Forza 250 Facelift.\nWindshield elektrik lancar.\nKondisi sangat istimewa, seperti baru.\nServis record Honda Big Wing.\nKenyamanan kelas atas.",
                'image' => 'products/beat_2022.jpg'
            ],

            // === SPORT 150-250CC ===
            [
                'name' => 'Kawasaki ZX-25R ABS SE 2022',
                'brand' => 'Kawasaki',
                'type' => 'Sport',
                'cc' => 250,
                'price' => 105000000,
                'year_manufacture' => 2022,
                'year_assembly' => 2022,
                'color' => 'KRT Green',
                'odometer' => 3000,
                'usage_type' => 'Jarang Pakai',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Mulus', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-11-20', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => true,
                'modifications' => 'Knalpot Yoshimura Full System (Ori ada)',
                'short_description' => '4 Silinder merdu. KM Low. Full Modif Branded.',
                'description' => "Kawasaki ZX-25R ABS SE Quickshifter.\nSuara 4 silinder melengking bikin candu.\nBarang simpanan, jarang kena hujan.\nSudah coating 3 layer.\nBonus paddock dan knalpot racing.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Yamaha R15M Connected 2022',
                'brand' => 'Yamaha',
                'type' => 'Sport',
                'cc' => 155,
                'price' => 35000000,
                'year_manufacture' => 2022,
                'year_assembly' => 2022,
                'color' => 'Silver Metallic',
                'odometer' => 11000,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Mulus', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-03-12', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => true,
                'short_description' => 'Rasa moge look. Quickshifter & TCS on.',
                'description' => "Yamaha R15M Connected ABS.\nFitur terlengkap di kelasnya: Quickshifter, Traction Control, ABS.\nTampilan mirip R1M.\nKondisi mulus terawat, bensin selalu Pertamax.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Honda CBR150R K45A 2015',
                'brand' => 'Honda',
                'type' => 'Sport',
                'cc' => 150,
                'price' => 14000000,
                'year_manufacture' => 2015,
                'year_assembly' => 2015,
                'color' => 'Repsol Edition',
                'odometer' => 55000,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Menggelitik', 'oil_leak' => 'Rembes', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Normal',
                'body_condition' => 'Lecet Parah', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-02-15', 'plate_number_status' => 'Asli',
                'routine_service' => false, 'service_book' => false, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => false, 'toolkit' => true, 'manual_book' => false, 'bonus_helmet' => false,
                'short_description' => 'CBR Lokal dual keen eyes. Mesin perlu servis ringan.',
                'description' => "Honda CBR150R K45A (CBR Lokal).\nMesin ada suara keteng (tensioner perlu ganti).\nFairing ada lecet bekas jatuh parkir.\nSurat lengkap pajak on.\nCocok buat bahan modif atau pemula sport.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Kawasaki Ninja 250 Karbu 2011',
                'brand' => 'Kawasaki',
                'type' => 'Sport',
                'cc' => 250,
                'price' => 19000000,
                'year_manufacture' => 2011,
                'year_assembly' => 2011,
                'color' => 'Merah',
                'odometer' => 62000,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Kasar', 'oil_leak' => 'Rembes', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Berat',
                'body_condition' => 'Repaint', 'frame_condition' => 'Normal', 'legs_condition' => 'Oblak', 'electrical_condition' => 'Perlu Perbaikan',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Mati', 'tax_expiry' => '2022-06-10', 'plate_number_status' => 'Asli',
                'routine_service' => false, 'service_book' => false, 'accident_history' => true, 'flood_history' => false, 'engine_overhaul' => true,
                'spare_key' => false, 'toolkit' => false, 'manual_book' => false, 'bonus_helmet' => false,
                'short_description' => 'Ninja 250 legendaris. Suara moge. Butuh perbaikan.',
                'description' => "Kawasaki Ninja 250R Karburator.\nMesin agak kasar, karbu perlu setting ulang.\nPernah jatuh ringan (fairing repaint).\nPajak mati 3 tahun.\nJual murah apa adanya buat bahan.",
                'image' => 'products/beat_2022.jpg'
            ],

            // === RETRO & CLASSIC ===
            [
                'name' => 'Yamaha XSR 155 2021',
                'brand' => 'Yamaha',
                'type' => 'Sport',
                'cc' => 155,
                'price' => 29000000,
                'year_manufacture' => 2021,
                'year_assembly' => 2021,
                'color' => 'Matte Silver',
                'odometer' => 15000,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Lecet Pemakaian', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-04-20', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => false,
                'modifications' => 'Spion Bar End, Jok Custom',
                'short_description' => 'Sport heritage ganteng. Siap kalcer.',
                'description' => "Yamaha XSR 155.\nGaya retro tapi mesin modern (VVA + Slipper Clutch).\nSudah modif tipis-tipis ganteng.\nMesin sehat walafiat.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Kawasaki W175 SE 2019',
                'brand' => 'Kawasaki',
                'type' => 'Sport',
                'cc' => 175,
                'price' => 21000000,
                'year_manufacture' => 2019,
                'year_assembly' => 2019,
                'color' => 'Silver',
                'odometer' => 10000,
                'usage_type' => 'Jarang Pakai',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Lecet Pemakaian', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-08-08', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => false,
                'short_description' => 'Klasik asik. Motor santai.',
                'description' => "Kawasaki W175 Special Edition.\nMotor karburator yang simple dan easy maintenance.\nKondisi body mulus, chrome masih kinclong.\nEnak buat jalan santai sore hari.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Royal Enfield Classic 350 2022',
                'brand' => 'Royal Enfield',
                'type' => 'Sport',
                'cc' => 350,
                'price' => 98000000,
                'year_manufacture' => 2022,
                'year_assembly' => 2022,
                'color' => 'Halcyon Green',
                'odometer' => 4000,
                'usage_type' => 'Jarang Pakai',
                'usage_location' => 'Luar Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Mulus', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-12-01', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => true,
                'short_description' => 'The true classic. Thump engine character.',
                'description' => "Royal Enfield Classic 350 Reborn.\nPlatform J-Series terbaru, getaran minim.\nKondisi like new, aksesoris engine guard original.\nSurat-surat resmi ATPM.",
                'image' => 'products/beat_2022.jpg'
            ],

            // === MOGE (BIG BIKES) ===
            [
                'name' => 'Kawasaki ER6n 2012',
                'brand' => 'Kawasaki',
                'type' => 'Moge',
                'cc' => 650,
                'price' => 75000000,
                'year_manufacture' => 2012,
                'year_assembly' => 2012,
                'color' => 'Merah',
                'odometer' => 45000,
                'usage_type' => 'Touring',
                'usage_location' => 'Luar Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Rembes', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Lecet Pemakaian', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Mati', 'tax_expiry' => '2024-02-10', 'plate_number_status' => 'Asli',
                'routine_service' => false, 'service_book' => false, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => false, 'toolkit' => true, 'manual_book' => false, 'bonus_helmet' => false,
                'short_description' => 'Moge pemula harga mocil. Torsi badak.',
                'description' => "Kawasaki ER6n 650cc 2 Silinder.\nFull Paper (FP) Plat B.\nPajak telat 1x.\nMesin sehat, ada rembes oli sedikit di paking blok kiri (penyakit umum).\nKnalpot custom full system (ori tidak ada).",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Honda CB500X 2019',
                'brand' => 'Honda',
                'type' => 'Moge',
                'cc' => 471,
                'price' => 145000000,
                'year_manufacture' => 2019,
                'year_assembly' => 2019,
                'color' => 'Grand Prix Red',
                'odometer' => 18000,
                'usage_type' => 'Touring',
                'usage_location' => 'Luar Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Mulus', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-05-15', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => true,
                'modifications' => 'Crashbar, Foglamp, Top Box Givi',
                'short_description' => 'Adventure tourer paling nyaman dan irit.',
                'description' => "Honda CB500X Facelift (Velg Depan 19 inch).\nSiap touring keliling Indonesia.\nAksesoris lengkap: Crashbar, Foglamp, Box.\nMesin sangat halus dan irit untuk kelas 500cc.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Kawasaki Z900 2018',
                'brand' => 'Kawasaki',
                'type' => 'Moge',
                'cc' => 948,
                'price' => 210000000,
                'year_manufacture' => 2018,
                'year_assembly' => 2018,
                'color' => 'Black Green',
                'odometer' => 12000,
                'usage_type' => 'Jarang Pakai',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Lecet Pemakaian', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-07-20', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => false,
                'short_description' => 'Sugomi design. 4 Silinder beringas.',
                'description' => "Kawasaki Z900 Full Paper.\nNik 2018 pemakaian 2019.\nSuara padat 4 silinder 900cc.\nKondisi mulus, cat original.\nBan Battlax S22 baru ganti.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Yamaha MT-09 2016',
                'brand' => 'Yamaha',
                'type' => 'Moge',
                'cc' => 850,
                'price' => 195000000,
                'year_manufacture' => 2016,
                'year_assembly' => 2016,
                'color' => 'Race Blue',
                'odometer' => 25000,
                'usage_type' => 'Touring',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Mulus', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-10-10', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => false, 'bonus_helmet' => false,
                'short_description' => 'Master of Torque. 3 Silinder Crossplane.',
                'description' => "Yamaha MT-09 FP Plat B.\nMesin 3 silinder CP3 yang punya karakter unik dan torsi jambak.\nMode berkendara A, STD, B normal semua.\nKelistrikan aman no malfunction.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Honda Rebel 500 2020',
                'brand' => 'Honda',
                'type' => 'Moge',
                'cc' => 471,
                'price' => 155000000,
                'year_manufacture' => 2020,
                'year_assembly' => 2020,
                'color' => 'Matte Jeans Blue',
                'odometer' => 8000,
                'usage_type' => 'Jarang Pakai',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Lecet Pemakaian', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-03-03', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => true,
                'short_description' => 'Bobber modern yang friendly.',
                'description' => "Honda CMX500 Rebel.\nFacelift sudah lampu LED semua dan ada Gear Indicator.\nPosisi riding santai, kaki napak sempurna.\nKondisi sangat terawat.",
                'image' => 'products/beat_2022.jpg'
            ],
            
            // === TRAIL & ADVENTURE ===
            [
                'name' => 'Honda CRF 150L 2022',
                'brand' => 'Honda',
                'type' => 'Trail',
                'cc' => 150,
                'price' => 29000000,
                'year_manufacture' => 2022,
                'year_assembly' => 2022,
                'color' => 'Extreme Black',
                'odometer' => 5000,
                'usage_type' => 'Trabas',
                'usage_location' => 'Luar Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Lecet Pemakaian', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-06-15', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => false,
                'modifications' => 'Stang Protaper, Ban Pacul Baru',
                'short_description' => 'Siap garuk tanah. Suspensi nyaman.',
                'description' => "Honda CRF 150L.\nMotor hobi, dipakai trabas ringan weekend.\nMesin standar, kelistrikan normal.\nBody baret wajar pemakaian offroad.",
                'image' => 'products/beat_2022.jpg'
            ],
            [
                'name' => 'Yamaha WR 155 R 2023',
                'brand' => 'Yamaha',
                'type' => 'Trail',
                'cc' => 155,
                'price' => 36000000,
                'year_manufacture' => 2023,
                'year_assembly' => 2023,
                'color' => 'Blue',
                'odometer' => 2000,
                'usage_type' => 'Harian',
                'usage_location' => 'Dalam Kota',
                'engine_sound' => 'Normal', 'oil_leak' => 'Kering', 'exhaust_smoke' => 'Normal', 'engine_pull' => 'Responsif',
                'body_condition' => 'Mulus', 'frame_condition' => 'Normal', 'legs_condition' => 'Stabil', 'electrical_condition' => 'Normal',
                'stnk_status' => 'Ada', 'bpkb_status' => 'Ada', 'tax_status' => 'Hidup', 'tax_expiry' => '2025-09-20', 'plate_number_status' => 'Asli',
                'routine_service' => true, 'service_book' => true, 'accident_history' => false, 'flood_history' => false, 'engine_overhaul' => false,
                'spare_key' => true, 'toolkit' => true, 'manual_book' => true, 'bonus_helmet' => true,
                'short_description' => 'Trail paling bertenaga di kelasnya.',
                'description' => "Yamaha WR 155 R VVA.\nMotor jangkung, tenaga paling besar 155cc VVA.\nBelum pernah siksa offroad, cuma pakai harian supermoto (ban ori tersimpan).\nKondisi like new.",
                'image' => 'products/beat_2022.jpg'
            ],
        ];

        foreach ($products as $data) {
            // Calculate slug
            $data['slug'] = Str::slug($data['name'] . '-' . $data['year_manufacture']);
            
            // Create model instance
            $product = new Product($data);
            
            // Calculate grade dynamically
            $product->grade = $product->calculateGrade();
            
            // Save
            $product->save();
        }
    }
}
